FROM mcr.microsoft.com/dotnet/sdk:10.0

WORKDIR /src

COPY ProductService.csproj .
RUN dotnet restore

COPY . .

RUN dotnet tool install --global dotnet-ef

ENV PATH="$PATH:/root/.dotnet/tools"

ENTRYPOINT ["dotnet", "ef"]
